const I18N={
 hu:{
  'Journal':'Napló','Progress':'Haladás','Explore & Secrets':'Felfedezés és titkok','Legendary Gunslingers':'Legendás pisztolyforgatók','Wildlife':'Állatnapló','Horse Register':'Lónyilvántartás','The People I Rode With':'Akikkel együtt lovagoltam','Campfire Memories':'Tábortűzi emlékek','Frontier Newspaper':'Határvidéki újság','Sketchbook':'Vázlatfüzet','Honor & Keepsake':'Becsület és emlék','Settings':'Beállítások',
  'What am I missing?':'Mi hiányzik még?','A place for the things between missions.':'A küldetések közötti felfedezések helye.','A page for the gang, memories and your own words.':'Oldal a bandának, az emlékeknek és a saját gondolataidnak.','Every good ride deserves a page.':'Minden jó lovaglás megérdemel egy saját oldalt.','The fire burns low. The road goes quiet.':'A tűz lassan elcsendesedik. Az út is elnémul.','Clippings, rumors and things worth remembering.':'Kivágások, pletykák és dolgok, amiket érdemes megőrizni.','Draw animals, maps, horses, faces, landmarks — whatever you want.':'Rajzolj állatokat, térképeket, lovakat, arcokat, tájakat — amit csak szeretnél.','Small things, kept safe.':'Apróságok, biztonságban megőrizve.',
  'Saved locally':'Helyben mentve','Saved just now':'Most mentve','journal progress':'napló haladása','progress':'haladás','Missions reveal themselves one at a time. Finish the current entry to reveal the next. · A küldetések egymás után oldódnak fel.':'A küldetések egyenként válnak láthatóvá. Teljesítsd az aktuálisat a következő feloldásához.',
  'WHAT HAPPENS HERE? · MI TÖRTÉNIK?':'MI TÖRTÉNIK ITT?','NEED HELP? · ENGLISH':'SEGÍTSÉG · ANGOL','SEGÍTSÉG · MAGYAR':'SEGÍTSÉG · MAGYAR','ENGLISH → MAGYAR · QUICK GLOSSARY':'ANGOL → MAGYAR · GYORS SZÓTÁR','MY NOTE · SAJÁT JEGYZET':'SAJÁT JEGYZET',
  'EN:':'EN:','HU:':'HU:','SPOILER-SAFE':'SPOILERBIZTOS','Previous entry required':'Az előző bejegyzést teljesíteni kell','Your own note / Saját megjegyzés...':'Saját megjegyzés...','LOGGED / FELJEGYEZVE':'FELJEGYEZVE','Logged':'Feljegyezve','Studied':'Tanulmányozva','Three-star specimen noted':'Háromcsillagos példány feljegyezve','Owned / ridden':'Birtokolt / meglovagolt','Bonding notes complete':'Kötődés feljegyezve','Page completed':'Oldal elkészült','Encounter / duel':'Találkozás / párbaj','Weapon / reward logged':'Fegyver / jutalom feljegyezve',
  'EXPORT SAVE':'MENTÉS EXPORTÁLÁSA','IMPORT SAVE':'MENTÉS IMPORTÁLÁSA','Change journal owner':'Napló tulajdonosának módosítása','Toggle night mode':'Éjszakai mód váltása','Reset all progress':'Összes haladás törlése','Backup':'Biztonsági mentés','Quest help · Küldetéssegítség':'Küldetéssegítség','Settings':'Beállítások','Saved sketches are stored locally in this browser.':'A mentett rajzok ebben a böngészőben tárolódnak.','Clear':'Törlés','Save sketch':'Rajz mentése',
  'The journal is not here to rush you. It is here to make sure the little things you wanted to see do not get lost.':'A napló nem azért van, hogy siettessen. Azért van, hogy a kis dolgok, amiket látni szerettél volna, ne vesszenek el.',
  'This page is sealed.':'Ez az oldal le van pecsételve.','It will not reveal its contents until you mark the story turning point yourself.':'A tartalma addig rejtve marad, amíg te nem jelölöd meg a történet fordulópontját.','I have reached the turning point':'Elértem a fordulópontot','Choose the journal\'s tone':'Válaszd ki a napló hangulatát','Set this only after you have reached the relevant point. Nothing here describes the ending.':'Ezt csak a megfelelő pont elérése után állítsd be. Itt nincs leírva a befejezés.','HIGH / MAGAS':'MAGAS','MIDDLE / KÖZEPES':'KÖZEPES','LOW / ALACSONY':'ALACSONY','A quiet page, drawn with care.':'Csendes oldal, gondosan megrajzolva.','A harsher page, ink heavy at the edges.':'Keményebb oldal, sötétebb tintával a széleken.','A worn page, somewhere between light and shadow.':'Megviselt oldal, valahol fény és árnyék között.','The page waits for your choice.':'Az oldal várja a választásodat.',
  'The trail begins with a story, then turns into a series of encounters.':'A nyom egy történettel kezdődik, majd találkozások sorozatává válik.','Study · Track · Remember · Hunt when you choose.':'Tanulmányozd · Kövesd · Jegyezd fel · Vadássz, amikor szeretnél.','Your current horse':'A jelenlegi lovad','Personal field notes':'Saját terepjegyzetek','YOUR CLIPPINGS':'SAJÁT KIVÁGÁSAID','LOCAL MAN KEEPS NOTES':'HELYI FÉRFI NAPLÓT VEZET','The Gang Around the Fire':'A banda a tűz körül','Keep this page as a memory album. Add your own supplied voice clips later; the ambient journal sound layer can remain separate.':'Tartsd meg ezt az oldalt emlékalbumként. Később hozzáadhatod a saját hangfájljaidat; a napló alap hangulati hangrétege külön maradhat.',
  'FIELD NOTES · 1899':'TEREPJEGYZETEK · 1899','WHO DOES THIS JOURNAL BELONG TO?':'KIHEZ TARTOZIK EZ A NAPLÓ?','Your name':'A neved','OPEN THE JOURNAL':'NAPLÓ MEGNYITÁSA','Choose your language':'Válassz nyelvet','A field book for the road, the camp, the animals, the people and the little things you would otherwise miss.':'Terepkönyv az úthoz, a táborhoz, az állatokhoz, az emberekhez és azokhoz az apróságokhoz, amiket különben könnyű lenne elszalasztani.'
 },
 en:{}
};
I18N.en=Object.fromEntries(Object.entries(I18N.hu).map(([k])=>[k,k]));
function t(s){return (I18N[state?.lang||'hu']||I18N.hu)[s]||s}
function translateDOM(){
 const dict=I18N[state.lang]||I18N.hu;
 const walk=n=>{if(n.nodeType===3){const raw=n.nodeValue.trim();if(raw&&dict[raw]) n.nodeValue=n.nodeValue.replace(raw,dict[raw]);} else n.childNodes?.forEach(walk)};
 document.body.childNodes.forEach(walk);
 const repl=(sel,prop)=>document.querySelectorAll(sel).forEach(el=>{const v=el[prop];if(dict[v])el[prop]=dict[v]});
 repl('#drawer button','textContent');
 repl('.paper-btn','textContent');
 repl('.lang-btn','textContent');
 const title=document.title; if(dict[title])document.title=dict[title];
 const inp=document.getElementById('ownerInput'); if(inp) inp.placeholder=t('Your name');
 const prompt=document.getElementById('ownerPrompt'); if(prompt)prompt.textContent=t('WHO DOES THIS JOURNAL BELONG TO?');
 const open=document.getElementById('openBtn'); if(open)open.textContent=t('OPEN THE JOURNAL');
}
const KEY='arthurJournal_v1'; const VERSION=4;
const chapters=[
{id:'I',name:'Chapter I',desc:'Colter and the beginning of the road.',missions:['Outlaws from the West','Enter, Pursued by a Memory','Old Friends','The Aftermath of Genesis','Who the Hell is Leviticus Cornwall?','Eastward Bound']},
{id:'II',name:'Chapter II',desc:'Horseshoe Overlook and the open country.',missions:['Polite Society, Valentine Style','Americans at Rest','Who Is Not Without Sin','Exit Pursued by a Bruised Ego','Paying a Social Call','A Quiet Time','Good, Honest, Snake Oil','We Loved Once and True','The Spines of America','Pouring Forth Oil','A Fisher of Men','An American Pastoral Scene','The Sheep and the Goats','Blessed are the Meek?','Money Lending and Other Sins','The First Shall Be Last','A Strange Kindness']},
{id:'III',name:'Chapter III',desc:'Clemens Point, Rhodes and the Braithwaites.',missions:['The New South','Further Questions of Female Suffrage','American Distillation','An Honest Mistake','The Course of True Love I–III','Advertising, the New American Art','Horse Flesh for Dinner','The Fine Joys of Tobacco','Friends in Very Low Places','Magicians for Sport','The Gilded Cage','Sodom? Back to Gomorrah','Preaching Forgiveness as He Went','Blessed are the Peacemakers','A Short Walk in a Pretty Town','Blood Feuds, Ancient and Modern','The Battle of Shady Belle']},
{id:'IV',name:'Chapter IV',desc:'Shady Belle, Saint Denis and the city.',missions:['The Joys of Civilization','Angelo Bronte, a Man of Honor','No, No and Thrice, No','The Gilded Cage','Horsemen, Apocalypses','Urban Pleasures','Country Pursuits','Revenge is a Dish Best Eaten','Banking, the Old American Art']},
{id:'V',name:'Chapter V',desc:'Guarma and the long way home.',missions:['Welcome to the New World','Savagery Unleashed','A Kind and Benevolent Despot','Hell Hath No Fury','Paradise Mercifully Departed','Dear Uncle Tacitus','Fleeting Joy','A Fork in the Road']},
{id:'VI',name:'Chapter VI',desc:'Arthur’s final chapter. Future entries stay hidden until unlocked.',missions:['Icarus and Friends','Visiting Hours','Just a Social Call','A Rage Unleashed','Goodbye, Dear Friend','Favored Sons','The Delights of Van Horn','The Bridge to Nowhere','Archeology for Beginners','Honor, Amongst Thieves','The Fine Art of Conversation','The Course of True Love IV–V','Mrs. Sadie Adler, Widow I–II','Of Men and Angels','The King’s Son','My Last Boy','Our Best Selves','Red Dead Redemption']},
{id:'E1',name:'Epilogue I',desc:'Pronghorn Ranch and a different kind of life.',missions:['The Wheel','Simple Pleasures','Farming, for Beginners','Fatherhood, for Beginners','Old Habits','Jim Milton Rides, Again?','Fatherhood, for Idiots','Motherhood','Gainful Employment','The Landowning Classes / Home of the Gentry?']},
{id:'E2',name:'Epilogue II',desc:'Beecher’s Hope.',missions:['Bare Knuckle Friendships','Home Improvement for Beginners','An Honest Day’s Labors','The Tool Box','A New Jerusalem','A Quick Favor for an Old Friend','Uncle’s Bad Day','The Best of Women and Men','Trying Again','A Really Big Bastard','A New Future Imagined','American Venom']},
{id:'100',name:'100% Completion',desc:'The road’s full checklist. Nothing here has to be rushed.',missions:[]}
];
const categories={explore:[['Bandit hideouts','Mark hideouts you have visited and note what you found.'],['Dreamcatchers','Track the dreamcatcher locations you discover.'],['Rock carvings','Record the carvings and their locations.'],['Points of Interest','Keep a list of landmarks, unusual sights and strange encounters.'],['Secret / rare weapons','Track unique weapons without revealing future locations.'],['Rare items','Keep notes for masks, trinkets, talismans and unusual finds.'],['Stranger missions','Track optional strangers and return visits.'],['Camp activities','Poker, dominoes, five-finger fillet, chores and camp moments.'],['100% checklist','Use the master progress page when you are ready.']],gunslingers:[['Flaco Hernandez','A gunslinger encounter near the northern lake. Log the encounter, duel and weapon without spoiling later steps.'],['Emmet Granger','A retired gunslinger living as a pig farmer. Log the encounter, duel and reward.'],['Billy Midnight','A legendary quick-draw specialist whose trail begins with a tavern lead.'],['Jim “Boy” Calloway','The central figure of the gunslinger trail and its final confrontation.']]};
const people=[['John Marston','Stubborn, capable and central to the gang’s story.'],['Dutch van der Linde','Charismatic leader whose plans keep expanding.'],['Hosea Matthews','Old hand, storyteller and careful thinker.'],['Sadie Adler','Fierce, determined and impossible to keep down.'],['Charles Smith','Quiet, capable and principled.'],['Lenny Summers','Young, thoughtful and eager to prove himself.'],['Javier Escuella','Loyal gunslinger, musician and member of the gang.'],['Bill Williamson','Blunt, loud and often in trouble.'],['Sean MacGuire','Reckless young outlaw with endless energy.'],['Micah Bell','Volatile and divisive member of the gang.']];
const wildlife=['American Bison','Pronghorn','Whitetail Deer','Elk','Moose','Black Bear','Grizzly Bear','Wolf','Coyote','Cougar','Fox','Rabbit','Raccoon','Badger','Opossum','Beaver','Muskrat','Boar','Panther','Alligator','Bald Eagle','Red-tailed Hawk','Great Horned Owl','Great Blue Heron','Snowy Egret'];
const horses=['American Standardbred','American Paint','Appaloosa','Arabian','Andalusian','Ardennes','Belgian Draft','Hungarian Half-bred','Kentucky Saddler','Missouri Fox Trotter','Morgan','Mustang','Nokota','Shire','Tennessee Walker','Thoroughbred'];
const missionHelp={
'Polite Society, Valentine Style':{en:'Ride into Valentine with the group and follow the prompts. Watch the objective tracker for who you need to approach next.',hu:'Lovasodjatok be Valentine-be a társasággal, és mindig a képernyőn jelzett célpontot kövesd. Ha elakadsz, nézd meg az aktuális objective-et.'},
'Americans at Rest':{en:'Go to the saloon in Valentine and follow the encounter as it develops. Stay close to the objective marker.',hu:'Menj a Valentine-i szalonhoz, majd kövesd az eseményt. Maradj az aktuális jelölés közelében.'},
'Who Is Not Without Sin':{en:'Look for the mission lead around the Valentine area. Once the objective is active, follow the marker and complete the recovery task.',hu:'A küldetés Valentine környékén indul. Aktiválás után kövesd a jelölést, majd teljesítsd a visszaszerzéssel kapcsolatos feladatot.'},
'Exit Pursued by a Bruised Ego':{en:'Prepare for a hunt with Hosea. Bring the required horse-related equipment and follow the trail rather than rushing ahead.',hu:'Hoseával vadászatra indulsz. Figyelj a lóval kapcsolatos felszerelésre, majd kövesd a nyomokat és ne rohanj előre.'},
'Paying a Social Call':{en:'Ride with the gang to the marked homestead. Approach carefully and follow the objective prompts during the confrontation.',hu:'Lovagolj a bandával a kijelölt tanyához. Óvatosan közelíts, és a harc közben mindig az aktuális célkitűzést kövesd.'},
'A Quiet Time':{en:'Meet Lenny in Valentine and stay with him as the night gets increasingly chaotic. Use the objective markers whenever the scene changes.',hu:'Találkozz Lennyvel Valentine-ben, majd kövesd őt az egyre kaotikusabb este során. Amikor változik a helyzet, figyeld az objective jelölést.'},
'Good, Honest, Snake Oil':{en:'Find the sheriff’s office in Valentine and accept the bounty work. Track the target and bring the wanted man back according to the mission prompt.',hu:'Keresd meg a seriff irodáját Valentine-ben, majd vállald el a fejvadászatot. Kövesd a célpontot, és a küldetés utasítása szerint juttasd vissza.'},
'We Loved Once and True':{en:'Read the letter and follow the marked meeting points. The mission is mostly about travelling between objectives and listening to the conversation.',hu:'Olvasd el a levelet, majd kövesd a megjelölt találkozási pontokat. Főleg az útvonalat és a beszélgetés közbeni objective-eket kell követned.'},
'The Spines of America':{en:'Ride with Hosea to the marked homestead and use the wagon objective as your guide. Keep an eye on the minimap.',hu:'Lovagolj Hoseával a kijelölt tanyához, majd a szekérhez kapcsolódó objective-et kövesd. A minimap sokat segít.'},
'Pouring Forth Oil':{en:'Complete the preparation steps before the final train sequence. If an objective is unavailable, check whether an earlier preparation entry is still unfinished.',hu:'A vonatos rész előtt végezd el az előkészítő feladatokat. Ha valami nem aktiválódik, nézd meg, maradt-e korábbi előkészítő küldetés.'},
'A Fisher of Men':{en:'Go fishing with Jack and follow the simple tutorial prompts. Keep the line under control and use the on-screen fishing instructions.',hu:'Menj el horgászni Jackkel, és kövesd a tutorial utasításait. Tartsd kontroll alatt a zsinórt, és figyeld a képernyőn megjelenő gombokat.'},
'An American Pastoral Scene':{en:'Ride with the gang to the marked area. Stay alert during the robbery setup and use cover when the firefight begins.',hu:'Lovagolj a bandával a kijelölt helyre. A rablás előkészítésénél figyelj, majd a lövöldözéskor használj fedezéket.'},
'The Sheep and the Goats':{en:'Help move the sheep toward Valentine, then follow the mission’s escalation. Use Dead Eye and cover when the objective turns into a gunfight.',hu:'Tereld a juhokat Valentine felé, majd kövesd a küldetés eszkalálódását. Lövöldözésnél használd a Dead Eye-t és a fedezéket.'},
'Blessed are the Meek?':{en:'Enter the marked settlement and deal with the prison-related objective. Follow the prompts for the escape and the ride away.',hu:'Menj a kijelölt településre, majd teljesítsd a börtönhöz kapcsolódó feladatot. A szökésnél és az elvonulásnál kövesd a jelöléseket.'},
'Money Lending and Other Sins':{en:'Visit the marked debtor and recover the gang’s money. The journal can track your own notes about how you handled the encounter.',hu:'Keresd fel a kijelölt adóst, és szerezd vissza a banda pénzét. A Journalban feljegyezheted, hogyan oldottad meg a helyzetet.'},
'The First Shall Be Last':{en:'Ride with the group to the marked area and search for the missing gang member. Follow the rescue objectives in order.',hu:'Lovagolj a csapattal a kijelölt helyre, majd keresd meg az eltűnt bandatagot. A mentési objective-eket sorrendben kövesd.'},
'A Strange Kindness':{en:'Ride with the gang to the marked location and investigate the situation there. Stay with the group and follow the changing objectives.',hu:'Lovagolj a bandával a kijelölt helyre, és vizsgáld meg a helyzetet. Maradj a csapattal, mert az objective-ek menet közben változhatnak.'}
};
function genericHelp(name){return {en:`Follow the current objective marker for “${name}”. If the objective changes, pause and read the new instruction before moving on. This guide intentionally paraphrases the goal instead of reproducing the game's exact text.`,hu:`Kövesd a(z) „${name}” aktuális céljelölését. Ha megváltozik a feladat, állj meg egy pillanatra és olvasd el az új utasítást. A Journal szándékosan saját szavakkal magyaráz, nem másolja a játék teljes szövegét.`}}
let state=load(); let view='journal';
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&s.version)return migrate(s)}catch{} return {version:VERSION,owner:'',chapter:'II',done:{},notes:{},settings:{night:false},honor:'unknown',audio:{},sketches:{},lang:'hu'}}
function migrate(s){s.version=VERSION;s.done=s.done||{};s.notes=s.notes||{};s.settings=s.settings||{};s.audio=s.audio||{};s.sketches=s.sketches||{};s.honor=s.honor||'unknown';s.lang=s.lang||'hu';return s}
function save(){localStorage.setItem(KEY,JSON.stringify(state));const e=$('#saveStatus');if(e){e.textContent=t('Saved just now');clearTimeout(save.t);save.t=setTimeout(()=>e.textContent=t('Saved locally'),900)}}
function unlocked(i){return i<2||state.done['chapter-complete-'+chapters[i-1].id]===true}
function missionUnlocked(c,i){return i===0||!!state.done[c.id+'-'+(i-1)]}
function pct(c){if(c.id==='100')return masterPct();return c.missions.length?Math.round(c.missions.filter((_,i)=>state.done[c.id+'-'+i]).length/c.missions.length*100):0}
function masterPct(){const groups=[...wildlife.map((_,i)=>'wild-'+i),...horses.map((_,i)=>'horse-'+i),...people.map((_,i)=>'person-'+i),...Object.keys(categories).flatMap(k=>categories[k].map((_,i)=>k+'-'+i))];const d=groups.filter(k=>state.done[k]).length;return Math.round(d/groups.length*100)}
function current(){return chapters.find(c=>c.id===state.chapter)||chapters[1]}
function renderNav(){const n=$('#chapterNav');n.innerHTML='';chapters.forEach((c,i)=>{const b=document.createElement('button');const ok=i<2||unlocked(i)||c.id==='100';b.textContent=ok?c.name:'🔒 '+c.name;b.disabled=!ok;b.className=c.id===state.chapter?'active':'';b.onclick=()=>{state.chapter=c.id;view='journal';save();render()};n.appendChild(b)})}
function checkbox(id,label,checked=false,sub=''){return `<div class="check-row"><input class="check" type="checkbox" data-id="${esc(id)}" ${checked?'checked':''}><label><b>${esc(label)}</b>${sub?`<small>${esc(sub)}</small>`:''}</label></div>`}
function missionHTML(c){return c.missions.map((name,i)=>{const id=c.id+'-'+i,ok=missionUnlocked(c,i),ch=!!state.done[id],help=missionHelp[name]||genericHelp(name);return `<div class="mission ${ok?'':'locked'}"><div class="mission-head"><input class="mission-check" type="checkbox" data-id="${id}" ${ch?'checked':''} ${ok?'':'disabled'}><div><h3>${ok?esc(name):'🔒 Previous entry required'}</h3>${ok?'<span class="tag">SPOILER-SAFE</span>':''}</div></div>${ok?`<div class="detail"><details><summary>WHAT HAPPENS HERE? · MI TÖRTÉNIK?</summary><p><b>EN:</b> This is a spoiler-light route note. Use the objective marker and the mission flow as your primary guide.</p><p><b>HU:</b> Ez egy spoilermentes útmutató. Elsősorban a játék aktuális objective jelölését és a küldetés menetét kövesd.</p></details><details><summary>NEED HELP? · ENGLISH</summary><p>${esc(help.en)}</p></details><details><summary>SEGÍTSÉG · MAGYAR</summary><p>${esc(help.hu)}</p></details><details><summary>ENGLISH → MAGYAR · QUICK GLOSSARY</summary><div class="glossary"><span><b>Objective</b> = cél / feladat</span><span><b>Go to</b> = menj ide</span><span><b>Find</b> = keresd meg</span><span><b>Follow</b> = kövesd</span><span><b>Return</b> = térj vissza</span><span><b>Pick up</b> = vedd fel</span><span><b>Interact</b> = lépj kapcsolatba / használd</span><span><b>Search</b> = kutasd át</span><span><b>Escape</b> = menekülj / szökj meg</span><span><b>Take cover</b> = keress fedezéket</span></div></details><details><summary>MY NOTE · SAJÁT JEGYZET</summary><textarea data-note="${id}" placeholder="Your own note / Saját megjegyzés...">${esc(state.notes[id]||'')}</textarea></details></div>`:''}</div>`}).join('')}
function renderJournal(){const c=current();$('#title').textContent=c.name;$('#content').innerHTML=`<h2>${esc(c.name)}</h2><div class="subhead">${esc(c.desc)}</div><div class="stamp">${pct(c)}% LOGGED</div>${c.missions.length?`<div class="bar"><i style="width:${pct(c)}%"></i></div><p class="small-note">Missions reveal themselves one at a time. Finish the current entry to reveal the next. · A küldetések egymás után oldódnak fel.</p>${missionHTML(c)}`:`<div class="section-grid">${categories.explore.map((x,i)=>cardCheck('explore-'+i,x[0],x[1])).join('')}</div>`}`;wireChecks();wireNotes()}
function cardCheck(id,title,desc){return `<div class="card"><h3>${esc(title)}</h3><p>${esc(desc)}</p>${checkbox(id,'Logged / Feljegyezve',!!state.done[id])}</div>`}
function renderDashboard(){let all=chapters.filter(c=>c.id!=='100');$('#title').textContent='Progress';$('#content').innerHTML=`<h2>What am I missing?</h2><div class="subhead">Mi hiányzik még?</div><div class="section-grid">${all.map(c=>`<div class="card"><h3>${esc(c.name)}</h3><p>${pct(c)}% complete · ${c.missions.filter((_,i)=>state.done[c.id+'-'+i]).length}/${c.missions.length} missions</p><div class="bar"><i style="width:${pct(c)}%"></i></div></div>`).join('')}<div class="card"><h3>Master checklist</h3><p>${masterPct()}% of journal side registers logged.</p><div class="bar"><i style="width:${masterPct()}%"></i></div></div></div><div class="quote-box">The journal is not here to rush you. It is here to make sure the little things you wanted to see do not get lost.</div>`}
function renderExplore(){ $('#title').textContent='Explore & Secrets';$('#content').innerHTML=`<h2>Explore & Secrets</h2><div class="subhead">A place for the things between missions.</div><div class="section-grid">${categories.explore.map((x,i)=>cardCheck('explore-'+i,x[0],x[1])).join('')}</div><h3 class="section-title">Personal field notes</h3><textarea data-note="explore-free" placeholder="Locations, discoveries, things you want to remember...">${esc(state.notes['explore-free']||'')}</textarea>`;wireChecks();wireNotes() }
function renderGunslingers(){ $('#title').textContent='Legendary Gunslingers';$('#content').innerHTML=`<h2>Legendary Gunslingers</h2><div class="subhead">The trail begins with a story, then turns into a series of encounters.</div><div class="section-grid">${categories.gunslingers.map((x,i)=>`<div class="card profile"><div class="portrait">✦</div><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p>${checkbox('gun-'+i,'Encounter / duel',!!state.done['gun-'+i])}${checkbox('gunweapon-'+i,'Weapon / reward logged',!!state.done['gunweapon-'+i])}<textarea data-note="gun-note-${i}" placeholder="Your note...">${esc(state.notes['gun-note-'+i]||'')}</textarea></div>`).join('')}</div>`;wireChecks();wireNotes()}
function renderWildlife(){ $('#title').textContent='Wildlife';$('#content').innerHTML=`<h2>Wildlife Register</h2><div class="subhead">Study · Track · Remember · Hunt when you choose.</div><p class="small-note">Use each animal as a field card. Keep your own notes for habitat, three-star specimens, study status and favorite locations.</p><div class="list-grid">${wildlife.map((a,i)=>`<div class="card animal"><h3>✦ ${esc(a)}</h3>${checkbox('wild-'+i,'Logged',!!state.done['wild-'+i])}<div class="mini-checks">${checkbox('wildstudy-'+i,'Studied',!!state.done['wildstudy-'+i])}${checkbox('wild3-'+i,'Three-star specimen noted',!!state.done['wild3-'+i])}</div><textarea data-note="wildnote-${i}" placeholder="Habitat / location / notes...">${esc(state.notes['wildnote-'+i]||'')}</textarea></div>`).join('')}</div>`;wireChecks();wireNotes()}
function renderHorses(){ $('#title').textContent='Horse Register';$('#content').innerHTML=`<h2>Horse Register</h2><div class="subhead">Every good ride deserves a page.</div><div class="list-grid">${horses.map((h,i)=>`<div class="card horse"><div class="horse-sketch">♞</div><h3>${esc(h)}</h3>${checkbox('horse-'+i,'Owned / ridden',!!state.done['horse-'+i])}${checkbox('horsebond-'+i,'Bonding notes complete',!!state.done['horsebond-'+i])}<textarea data-note="horsenote-${i}" placeholder="Name · coat · bonding · memories...">${esc(state.notes['horsenote-'+i]||'')}</textarea></div>`).join('')}</div><div class="card"><h3>Your current horse</h3><textarea data-note="current-horse" placeholder="Name, breed, coat, where you found them, favorite memories...">${esc(state.notes['current-horse']||'')}</textarea></div>`;wireChecks();wireNotes()}
function renderPeople(){ $('#title').textContent='The People I Rode With';$('#content').innerHTML=`<h2>The People I Rode With</h2><div class="subhead">A page for the gang, memories and your own words.</div><div class="section-grid">${people.map((p,i)=>`<div class="card profile"><div class="portrait">✦</div><h3>${esc(p[0])}</h3><p>${esc(p[1])}</p>${checkbox('person-'+i,'Page completed',!!state.done['person-'+i])}<textarea data-note="person-note-${i}" placeholder="Your note about them...">${esc(state.notes['person-note-'+i]||'')}</textarea><div class="audio-box"><input type="file" accept="audio/*" data-audio="person-${i}"><span>${state.audio['person-'+i]?'Audio attached':'Add your own audio later'}</span>${state.audio['person-'+i]?`<audio controls src="${state.audio['person-'+i]}"></audio>`:''}</div></div>`).join('')}</div>`;wireChecks();wireNotes();wireAudio()}
function renderMemories(){ $('#title').textContent='Campfire Memories';$('#content').innerHTML=`<h2>Campfire Memories</h2><div class="subhead">The fire burns low. The road goes quiet.</div><div class="memories"><div><div class="fire">🔥</div><h3>The Gang Around the Fire</h3><p>Keep this page as a memory album. Add your own supplied voice clips later; the ambient journal sound layer can remain separate.</p><textarea data-note="campfire" placeholder="Write what you remember from camp...">${esc(state.notes.campfire||'')}</textarea><input type="file" accept="audio/*" data-audio="campfire"><br><br>${state.audio.campfire?`<audio controls src="${state.audio.campfire}"></audio>`:''}</div></div>`;wireNotes();wireAudio()}
function renderNewspaper(){ $('#title').textContent='Frontier Newspaper';$('#content').innerHTML=`<h2>The Frontier Ledger</h2><div class="subhead">Clippings, rumors and things worth remembering.</div><div class="newspaper"><div class="headline">LOCAL MAN KEEPS NOTES</div><p>Travelers report that a certain outlaw has become strangely organized. Witnesses say he carries a field book.</p><div class="rule"></div><h3>YOUR CLIPPINGS</h3><textarea data-note="newspaper" placeholder="Write your own headlines, discoveries, funny moments or reminders...">${esc(state.notes.newspaper||'')}</textarea></div>`;wireNotes()}
function renderSketchbook(){ $('#title').textContent='Sketchbook';$('#content').innerHTML=`<h2>Sketchbook</h2><div class="subhead">Draw animals, maps, horses, faces, landmarks — whatever you want.</div><div class="sketch-box"><canvas id="canvas" width="900" height="500"></canvas><div class="toolbar"><button id="clearCanvas">Clear</button><button id="saveCanvas">Save sketch</button></div></div><p class="small-note">Saved sketches are stored locally in this browser.</p>`;setupCanvas()}
function renderHonor(){ $('#title').textContent='Honor & Keepsake';const unlockedHonor=state.done['honor-unlock'];const h=state.honor;$('#content').innerHTML=`<h2>Honor & Keepsake</h2><div class="subhead">A page that stays closed until the story says it is time.</div>${!unlockedHonor?`<div class="locked-keepsake"><div class="seal">🔒</div><h3>This page is sealed.</h3><p>It will not reveal its contents until you mark the story turning point yourself.</p><button class="paper-btn" id="unlockHonor">I have reached the turning point</button></div>`:`<div class="keepsake"><div class="stamp">KEEPSAKE</div><h3>Choose the journal's tone</h3><p>Set this only after you have reached the relevant point. Nothing here describes the ending.</p><div class="honor-buttons"><button data-honor="high">HIGH / MAGAS</button><button data-honor="middle">MIDDLE / KÖZEPES</button><button data-honor="low">LOW / ALACSONY</button></div><div class="honor-art">${h==='high'?'✦ A quiet page, drawn with care.':h==='low'?'✦ A harsher page, ink heavy at the edges.':h==='middle'?'✦ A worn page, somewhere between light and shadow.':'✦ The page waits for your choice.'}</div></div>`}`;const u=$('#unlockHonor');if(u)u.onclick=()=>{state.done['honor-unlock']=true;save();renderHonor()};document.querySelectorAll('[data-honor]').forEach(b=>b.onclick=()=>{state.honor=b.dataset.honor;save();renderHonor()})}
function renderSettings(){ $('#title').textContent='Settings';$('#content').innerHTML=`<h2>Settings</h2><div class="subhead">Small things, kept safe.</div><div class="settings-grid"><button id="rename">✎ Change journal owner</button><button id="toggleNight">☾ Toggle night mode</button><button id="resetProgress">↺ Reset all progress</button><div class="language-settings"><b>Language / Nyelv</b><button id="setHu">🇭🇺 Magyar</button><button id="setEn">🇬🇧 English</button></div></div><div class="card" style="margin-top:18px"><h3>Quest help · Küldetéssegítség</h3><p>Every unlocked mission now has bilingual, spoiler-light help. The guide uses paraphrases rather than reproducing the game's full dialogue or objective text.</p></div><div class="card"><h3>Backup</h3><p>Export before changing browsers or devices. Import the JSON on the other device.</p></div>`;$('#setHu').onclick=()=>setLanguage('hu');$('#setEn').onclick=()=>setLanguage('en');$('#rename').onclick=()=>{const n=prompt('Journal owner:',state.owner);if(n!==null){state.owner=n.trim()||state.owner;save();render()}};$('#toggleNight').onclick=toggleNight;$('#resetProgress').onclick=()=>{if(confirm('Reset all journal progress?')){state.done={};state.notes={};state.honor='unknown';save();render()}}}
function wireChecks(){document.querySelectorAll('[data-id]').forEach(x=>x.onchange=()=>{state.done[x.dataset.id]=x.checked;if(x.checked&&x.dataset.id.match(/^(I|II|III|IV|V|VI|E1|E2)-\d+$/)){const [cid,i]=x.dataset.id.split('-');const c=chapters.find(c=>c.id===cid);if(c&&Number(i)===c.missions.length-1)state.done['chapter-complete-'+cid]=true}save();render()})}
function wireNotes(){document.querySelectorAll('[data-note]').forEach(x=>x.oninput=()=>{state.notes[x.dataset.note]=x.value;save()})}
function wireAudio(){document.querySelectorAll('[data-audio]').forEach(inp=>inp.onchange=()=>{const f=inp.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.audio[inp.dataset.audio]=r.result;save();render()};r.readAsDataURL(f)})}
function setupCanvas(){const c=$('#canvas');if(!c)return;const ctx=c.getContext('2d');ctx.fillStyle='#ead8b4';ctx.fillRect(0,0,c.width,c.height);let drawing=false;const pos=e=>{const r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*c.width/r.width,y:(p.clientY-r.top)*c.height/r.height}};const down=e=>{drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()};const move=e=>{if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.strokeStyle='#3b281b';ctx.lineWidth=3;ctx.lineCap='round';ctx.stroke();e.preventDefault()};const up=()=>drawing=false;c.onpointerdown=down;c.onpointermove=move;c.onpointerup=up;c.onpointercancel=up;$('#clearCanvas').onclick=()=>{ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#ead8b4';ctx.fillRect(0,0,c.width,c.height)};$('#saveCanvas').onclick=()=>{state.sketches.main=c.toDataURL('image/png');save();alert('Sketch saved in this browser.')};if(state.sketches.main){const im=new Image();im.onload=()=>ctx.drawImage(im,0,0);im.src=state.sketches.main}}
function toggleNight(){state.settings.night=!state.settings.night;document.body.classList.toggle('night',state.settings.night);save()}
function render(){document.body.classList.toggle('night',!!state.settings.night);$('#ownerLabel').textContent=state.owner?state.owner+"'s Journal":'Your Journal';const p=state.chapter==='100'?masterPct():pct(current());$('#progressPct').textContent=p+'%';$('#progressRing').style.setProperty('--p',p+'%');$('#progressText').textContent=view==='journal'?current().name+' progress':'journal progress';renderNav();({journal:renderJournal,dashboard:renderDashboard,explore:renderExplore,gunslingers:renderGunslingers,wildlife:renderWildlife,horses:renderHorses,people:renderPeople,memories:renderMemories,newspaper:renderNewspaper,sketchbook:renderSketchbook,honor:renderHonor,settings:renderSettings}[view]||renderJournal)();translateDOM()}
function setLanguage(lang){state.lang=lang;save();document.documentElement.lang=lang;document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.id===(lang==='hu'?'langHu':'langEn')));translateDOM();if(state.owner){render()}}
$('#langHu').onclick=()=>setLanguage('hu');$('#langEn').onclick=()=>setLanguage('en');
$('#openBtn').onclick=()=>{const n=$('#ownerInput').value.trim();if(!n)return $('#ownerInput').focus();state.owner=n;save();$('#intro').classList.add('hidden');$('#app').classList.remove('hidden');render()};$('#menuBtn').onclick=()=>$('#drawer').classList.toggle('open');$('#nightBtn').onclick=toggleNight;document.querySelectorAll('#drawer button').forEach(b=>b.onclick=()=>{$('#drawer').classList.remove('open');view=b.dataset.view;render()});$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='arthur-journal-save.json';a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=migrate(JSON.parse(r.result));save();$('#intro').classList.add('hidden');$('#app').classList.remove('hidden');render();}catch{alert('Invalid save file.')}};r.readAsText(f)};
if(state.owner){$('#intro').classList.add('hidden');$('#app').classList.remove('hidden');render()}
